apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: businessautomation-operator.1.1.1
  namespace: placeholder
  annotations:
    categories: "Integration & Delivery"
    capabilities: "Basic Install"
    certified: "true"
    description: Business Automation Operator for deployment and management of RHPAM/RHDM environments.
    repository: https://github.com/kiegroup/kie-cloud-operator    
    containerImage: registry.redhat.io/rhpam-7/rhpam74-operator:1.1
    createdAt: 2019-06-03
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{"apiVersion":"app.kiegroup.org/v1","kind":"KieApp","metadata":{"name":"rhpam-trial"},"spec":{"environment":"rhpam-trial"}}]
  labels:
    operator-businessautomation: "true"
spec:
  displayName: Business Automation
  description: Business Automation Operator for deployment and management of RHPAM/RHDM environments.
  keywords:
    - kieapp
    - pam
    - decision
    - kie
    - cloud
    - bpm
    - process
    - automation
    - operator
  version: 1.1.1
  maturity: stable
  maintainers:
    - name: Red Hat, Inc.
      email: bsig-cloud@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-process-automation-manager
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.4/#category-deploying-red-hat-process-automation-manager-on-openshift
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMH0uY2xzLTJ7ZmlsbDojYzIxYTAwfS5jbHMtM3tmaWxsOiNmZmZ9LmNscy00e2ZpbGw6I2VhZWFlYX0uY2xzLTV7ZmlsbDojYjdiN2I3fS5jbHMtNntmaWxsOiNjZGNkY2R9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0icm90YXRlKC00NSA1MCA1MCkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiAxNC42NGE1MCA1MCAwIDAgMS03MC43MiA3MC43MnoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02NS43NiAzNC4yOEwxNS42IDQzLjE1djEuMTNhLjM0LjM0IDAgMCAwIC4zLjM0YzEuNDcuMTcgNy45MyAyLjExIDggMjMuNDlhLjQ2LjQ2IDAgMCAwIC4zNS40NGwyLjU5LjU3cy0xLjIxLTI1LjU0IDguNzctMjcuMDYgMTEuMiAyNy4yNyAxMS4zMyAzMS4xYS41NC41NCAwIDAgMCAuNDMuNTFsMy41MS43OHMuMDYtMzQuNTQgMTQuOTItMzYuODJ2LTMuMzV6Ii8+PHBhdGggY2xhc3M9ImNscy00IiBkPSJNNjUuMzUgMjcuNTZMMTYuMTggMzguNDJhLjc1Ljc1IDAgMCAwLS41OS43M3Y0bDUwLjE3LTguODd2LTYuNzZhMS42OCAxLjY4IDAgMCAwLS40MS4wNHoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0zNS42MSA0Mi4wNWMtNC42MS43LTYuODMgNi41NC03Ljg5IDEyLjYxbDEzLjY1LTEuMzNjMC0uMTcuMDktLjM0LjEzLS41MXMuMTQtLjUzLjIxLS44bC4yLS42OHEuMTItLjQuMjUtLjhsLjItLjYyYy4xMi0uMzYuMjUtLjcxLjM5LTEuMDZsLjEyLS4zMmMtMS42NC00LjE3LTMuOTgtNi45OS03LjI2LTYuNDl6TTgyLjIzIDMxLjE5bC0xNi0zLjYyYTEuOSAxLjkgMCAwIDAtLjQyIDB2Ni43NmwxNy4wNiAyLjgzdi01LjIzYS43Ni43NiAwIDAgMC0uNjQtLjc0ek01My40MyA1My42MmwxOC40MS0xLjEzYzIuMS02LjA1IDUuNTEtMTEuNzUgMTEtMTIuOGwtMTctMi4wOGMtNi42OCAxLjEyLTEwLjM2IDguMjktMTIuNDEgMTYuMDF6Ii8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNNDEuNzEgNTJsLjEzLS40NS0uMTMuNDZ6TTQxLjkxIDUxLjM0bC0uMDYuMjIuMDctLjIzek0yNy43MiA1NC42NmE2OC4yNiA2OC4yNiAwIDAgMC0uOTMgMTJ2Mi40MkwzOSA2Ni4xYTEuMDYgMS4wNiAwIDAgMCAuODEtMSA1OC43MiA1OC43MiAwIDAgMSAxLjY5LTEyLjI2YzAgLjE2LS4wOS4zMy0uMTMuNDl6TTY1Ljc4IDM0LjI4bC4wMSAzLjM0IDE3LjAzIDIuMDd2LTIuNThsLTE3LjA0LTIuODN6TTUwLjg3IDc0LjQ0TDY4IDY4LjY4YS45Mi45MiAwIDAgMCAuNjMtLjc5IDcyLjQ2IDcyLjQ2IDAgMCAxIDMuMTgtMTUuNGwtMTguMzggMS4xM2E5MC45MSA5MC45MSAwIDAgMC0yLjU2IDIwLjgyek01My40MyA1My42MnoiLz48L2c+PC9zdmc+
      mediatype: image/svg+xml
  labels:
    alm-owner-businessautomation: businessautomation-operator
    operated-by: businessautomation-operator.1.1.1
  selector:
    matchLabels:
      alm-owner-businessautomation: businessautomation-operator
      operated-by: businessautomation-operator.1.1.1
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - version: v1
        kind: KieApp
        description: A project prescription running an RHPAM/RHDM environment.
        displayName: KieApp
        name: kieapps.app.kiegroup.org
        resources:
          - kind: DeploymentConfig
            version: apps.openshift.io/v1
          - kind: StatefulSet
            version: apps/v1
          - kind: Secret
            version: v1
          - kind: PersistentVolumeClaim
            version: v1
          - kind: ServiceAccount
            version: v1
          - kind: Role
            version: authorization.openshift.io/v1
          - kind: RoleBinding
            version: authorization.openshift.io/v1
          - kind: Service
            version: v1
          - kind: Route
            version: route.openshift.io/v1
          - kind: BuildConfig
            version: build.openshift.io/v1
          - kind: ImageStream
            version: image.openshift.io/v1
        specDescriptors:
          - description: Environment deployed.
            displayName: Environment
            path: environment
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
          - description: Product version installed.
            displayName: Version
            path: commonConfig.version
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
        statusDescriptors:
          - description: Deployments for the KieApp environment.
            displayName: Deployments
            path: deployments
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
          - description: The address for accessing Business Central, if it is deployed.
            displayName: Business/Decision Central URL
            path: consoleHost
            x-descriptors:
              - "urn:alm:descriptor:org.w3:link"
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: business-automation-operator
          rules:
            - apiGroups:
                - ""
                - apps
                - app.kiegroup.org
                - rbac.authorization.k8s.io
                - apps.openshift.io
                - image.openshift.io
                - build.openshift.io
                - route.openshift.io
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - operators.coreos.com
              resources:
                - clusterserviceversions
              verbs:
                - "*"
            - apiGroups:
                - apps
              resourceNames:
                - kie-cloud-operator
                - business-automation-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
      deployments:
        - name: business-automation-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                name: business-automation-operator
            template:
              metadata:
                labels:
                  name: business-automation-operator
              spec:
                serviceAccountName: business-automation-operator
                containers:
                  - name: business-automation-operator
                    image: registry.redhat.io/rhpam-7/rhpam74-operator:1.1
                    command:
                      - kie-cloud-operator
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.labels['name']
                      - name: OPERATOR_UI
                        value: "true"
