## KIE smartrouter BEGIN
smartrouter:
  omit: true
## KIE smartrouter END
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #{{ range $index, $Map := .Servers }}
  ## PostgreSQL persistent volume claim BEGIN
  - persistentVolumeClaims:
      - metadata:
          name: "{{$.ApplicationName}}-postgresql-claim-{{$index}}"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{$.ApplicationName}}-postgresql-{{$index}}"
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "1Gi"
    ## PostgreSQL persistent volume claim END
    ## KIE server build config BEGIN
    #{{if .Build.KieServerContainerDeployment}}
    imageStreams:
      - metadata:
          name: "{{$.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{$.ApplicationName}}-kieserver-{{$index}}"
    buildConfigs:
      - metadata:
          name: "{{$.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{$.ApplicationName}}-kieserver-{{$index}}"
        spec:
          source:
            type: Git
            git:
              uri: "{{.Build.GitSource.URI}}"
              ref: "{{.Build.GitSource.Reference}}"
            contextDir: "{{.Build.GitSource.ContextDir}}"
          strategy:
            type: Source
            sourceStrategy:
              env:
                - name: KIE_SERVER_CONTAINER_DEPLOYMENT
                  value: "{{.Build.KieServerContainerDeployment}}"
                - name: MAVEN_MIRROR_URL
                  value: "{{.Build.MavenMirrorURL}}"
                - name: ARTIFACT_DIR
                  value: "{{.Build.ArtifactDir}}"
              forcePull: true
              from:
                kind: "{{.Build.From.Kind}}"
                namespace: "{{.Build.From.Namespace}}"
                name: "{{.Build.From.Name}}"
          output:
            to:
              kind: ImageStreamTag
              name: "{{$.ApplicationName}}-kieserver-{{$index}}:latest"
          triggers:
            - type: GitHub
              github:
                secret: "{{.Build.GitHubWebhookSecret}}"
            - type: Generic
              generic:
                secret: "{{.Build.GenericWebhookSecret}}"
            - type: ImageChange
              imageChange: {}
            - type: ConfigChange
    #{{end}}
    ## KIE server build config END
    ## KIE server deployment config BEGIN
    deploymentConfigs:
      - metadata:
          name: "{{$.ApplicationName}}-kieserver-{{$index}}"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{$.ApplicationName}}-kieserver-{{$index}}"
        spec:
          replicas: 2
          template:
            spec:
              containers:
                - name: "{{$.ApplicationName}}-kieserver-{{$index}}"
                  image: "{{$.ApplicationName}}-kieserver-{{$index}}"
                  env:
                    - name: KIE_SERVER_CONTAINER_DEPLOYMENT
                      value: "{{.Build.KieServerContainerDeployment}}"
                    - name: KIE_SERVER_MGMT_DISABLED
                      value: "true"
                    - name: KIE_SERVER_STARTUP_STRATEGY
                      value: LocalContainersStartupStrategy
                    - name: "{{$.MavenRepo}}_MAVEN_REPO_USERNAME"
                      value: ""
                    - name: "{{$.MavenRepo}}_MAVEN_REPO_PASSWORD"
                      value: ""
                    - name: "{{$.MavenRepo}}_MAVEN_REPO_SERVICE"
                      value: ""
                    - name: MAVEN_REPOS
                      value: "EXTERNAL"
                    - name: KIE_SERVER_ROUTER_PROTOCOL
                      value: "http"
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    ## PostgreSQL driver settings BEGIN
                    - name: RHPAM_DRIVER
                      value: "postgresql"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.PostgreSQLDialect"
                    - name: RHPAM_USERNAME
                      value: "rhpam"
                    - name: RHPAM_PASSWORD
                      value: "{{$.AdminPassword}}"
                    - name: RHPAM_SERVICE_HOST
                      value: "{{$.ApplicationName}}-postgresql-{{$index}}"
                    - name: RHPAM_SERVICE_PORT
                      value: "5432"
                    - name: TIMER_SERVICE_DATA_STORE
                      value: "{{$.ApplicationName}}-postgresql-{{$index}}"
                    - name: TIMER_SERVICE_DATA_STORE_REFRESH_INTERVAL
                      value: "30000"
                    ## PostgreSQL driver settings END
      ## KIE server deployment config END
      ## PostgreSQL deployment config BEGIN
      - metadata:
          name: "{{$.ApplicationName}}-postgresql-{{$index}}"
          labels:
            app: "{{$.ApplicationName}}"
            application: "{{$.ApplicationName}}"
            service: "{{$.ApplicationName}}-postgresql-{{$index}}"
        spec:
          strategy:
            type: Recreate
          triggers:
            - type: ImageChange
              imageChangeParams:
                automatic: true
                containerNames:
                  - "{{$.ApplicationName}}-postgresql"
                from:
                  kind: ImageStreamTag
                  namespace: "openshift"
                  name: "postgresql:10"
            - type: ConfigChange
          replicas: 1
          selector:
            deploymentConfig: "{{$.ApplicationName}}-postgresql-{{$index}}"
          template:
            metadata:
              name: "{{$.ApplicationName}}-postgresql-{{$index}}"
              labels:
                deploymentConfig: "{{$.ApplicationName}}-postgresql-{{$index}}"
                app: "{{$.ApplicationName}}"
                application: "{{$.ApplicationName}}"
                service: "{{$.ApplicationName}}-postgresql-{{$index}}"
            spec:
              containers:
                - name: "{{$.ApplicationName}}-postgresql"
                  image: postgresql
                  imagePullPolicy: IfNotPresent
                  livenessProbe:
                    exec:
                      command:
                        - "/usr/libexec/check-container"
                        - "--live"
                    initialDelaySeconds: 120
                    timeoutSeconds: 10
                  readinessProbe:
                    exec:
                      command:
                        - "/usr/libexec/check-container"
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  ports:
                    - containerPort: 5432
                      protocol: TCP
                  volumeMounts:
                    - mountPath: "/var/lib/pgsql/data"
                      name: "{{$.ApplicationName}}-postgresql-pvol"
                  env:
                    - name: POSTGRESQL_USER
                      value: "rhpam"
                    - name: POSTGRESQL_PASSWORD
                      value: "{{$.AdminPassword}}"
                    - name: POSTGRESQL_DATABASE
                      value: "rhpam7"
                    - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
                      value: "100"
              volumes:
                - name: "{{$.ApplicationName}}-postgresql-pvol"
                  persistentVolumeClaim:
                    claimName: "{{$.ApplicationName}}-postgresql-claim-{{$index}}"
    ## PostgreSQL deployment config END
    services:
      ## PostgreSQL service BEGIN
      - metadata:
          annotations:
            description: The database server's port.
          labels:
            application: prod
            service: "{{$.ApplicationName}}-postgresql-{{$index}}"
          name: "{{$.ApplicationName}}-postgresql-{{$index}}"
        spec:
          ports:
            - port: 5432
              targetPort: 5432
          selector:
            deploymentConfig: "{{$.ApplicationName}}-postgresql-{{$index}}"
    ## PostgreSQL service END
#{{end}}
## RANGE ends
## KIE Servers END
