#! package-manifest: deploy/catalog_resources/community/7.8/kiecloud-operator.7.8.2.clusterserviceversion.yaml
channels:
- currentCSV: kiecloud-operator.7.8.2
  name: stable
packageName: kiecloud-operator
