apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: process-migration-externaldb
  annotations:
    consoleName: snippet-process-migration-externaldb
    consoleTitle: Configure PIM with external DB
    consoleDesc: Use this snippet to configure pim with external db
    consoleSnippet: true
spec:
  objects:
    processMigration:
      username: pimAdmin
      password: somePasswordThatWillBeConvertedToMD5
      database:
        type: external
        externalConfig:
          # for all supported Quarks JDBC extensions please visit https://quarkus.io/guides/datasource
          driver: mssql
          jdbcURL: jdbc:sqlserver://10.10.10.20:1433;DatabaseName=rhpam
          username: pim
          password: pim
          minPoolSize: "10"
          maxPoolSize: "10"

