apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"app.kiegroup.org/v2","kind":"KieApp","metadata":{"name":"rhpam-trial"},"spec":{"environment":"rhpam-trial"}}]'
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "false"
    containerImage: quay.io/kiegroup/kie-cloud-operator:1.4.0
    createdAt: "2020-02-17 12:02:25"
    description: Kie Cloud Operator for deployment and management of RHPAM/RHDM environments.
    repository: https://github.com/kiegroup/kie-cloud-operator
    support: Red Hat, Inc.
    tectonic-visibility: ocs
  labels:
    operator-kiecloud: "true"
  name: kiecloud-operator.1.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: A project prescription running an RHPAM/RHDM environment.
      displayName: KieApp
      kind: KieApp
      name: kieapps.app.kiegroup.org
      resources:
      - kind: DeploymentConfig
        name: ""
        version: apps.openshift.io/v1
      - kind: StatefulSet
        name: ""
        version: apps/v1
      - kind: Role
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: RoleBinding
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: Route
        name: ""
        version: route.openshift.io/v1
      - kind: BuildConfig
        name: ""
        version: build.openshift.io/v1
      - kind: ImageStream
        name: ""
        version: image.openshift.io/v1
      - kind: Secret
        name: ""
        version: v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: Set true to enable automatic micro version product upgrades,
          it is disabled by default.
        displayName: Enable Upgrades
        path: upgrades.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Set true to enable automatic minor product version upgrades,
          it is disabled by default. Requires spec.upgrades.enabled to be true.
        displayName: Include minor version upgrades
        path: upgrades.minor
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Set true to enable image tags, disabled by default. This will
          leverage image tags instead of the image digests.
        displayName: Use Image Tags
        path: useImageTags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Environment deployed.
        displayName: Environment
        path: environment
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Product version installed.
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      statusDescriptors:
      - description: Deployments for the KieApp environment.
        displayName: Deployments
        path: deployments
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Current phase.
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: The address for accessing Business Central, if it is deployed.
        displayName: Business/Decision Central URL
        path: consoleHost
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      version: v2
  description: Kie Cloud Operator for deployment and management of RHPAM/RHDM environments.
  displayName: Kie Cloud
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2Q3MWUwMH0uY2xzLTJ7ZmlsbDojYzIxYTAwfS5jbHMtM3tmaWxsOiNmZmZ9LmNscy00e2ZpbGw6I2VhZWFlYX0uY2xzLTV7ZmlsbDojYjdiN2I3fS5jbHMtNntmaWxsOiNjZGNkY2R9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkxvZ288L3RpdGxlPjxnIGlkPSJMYXllcl8xIiBkYXRhLW5hbWU9IkxheWVyIDEiPjxjaXJjbGUgY2xhc3M9ImNscy0xIiBjeD0iNTAiIGN5PSI1MCIgcj0iNTAiIHRyYW5zZm9ybT0icm90YXRlKC00NSA1MCA1MCkiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik04NS4zNiAxNC42NGE1MCA1MCAwIDAgMS03MC43MiA3MC43MnoiLz48cGF0aCBjbGFzcz0iY2xzLTMiIGQ9Ik02NS43NiAzNC4yOEwxNS42IDQzLjE1djEuMTNhLjM0LjM0IDAgMCAwIC4zLjM0YzEuNDcuMTcgNy45MyAyLjExIDggMjMuNDlhLjQ2LjQ2IDAgMCAwIC4zNS40NGwyLjU5LjU3cy0xLjIxLTI1LjU0IDguNzctMjcuMDYgMTEuMiAyNy4yNyAxMS4zMyAzMS4xYS41NC41NCAwIDAgMCAuNDMuNTFsMy41MS43OHMuMDYtMzQuNTQgMTQuOTItMzYuODJ2LTMuMzV6Ii8+PHBhdGggY2xhc3M9ImNscy00IiBkPSJNNjUuMzUgMjcuNTZMMTYuMTggMzguNDJhLjc1Ljc1IDAgMCAwLS41OS43M3Y0bDUwLjE3LTguODd2LTYuNzZhMS42OCAxLjY4IDAgMCAwLS40MS4wNHoiLz48cGF0aCBjbGFzcz0iY2xzLTUiIGQ9Ik0zNS42MSA0Mi4wNWMtNC42MS43LTYuODMgNi41NC03Ljg5IDEyLjYxbDEzLjY1LTEuMzNjMC0uMTcuMDktLjM0LjEzLS41MXMuMTQtLjUzLjIxLS44bC4yLS42OHEuMTItLjQuMjUtLjhsLjItLjYyYy4xMi0uMzYuMjUtLjcxLjM5LTEuMDZsLjEyLS4zMmMtMS42NC00LjE3LTMuOTgtNi45OS03LjI2LTYuNDl6TTgyLjIzIDMxLjE5bC0xNi0zLjYyYTEuOSAxLjkgMCAwIDAtLjQyIDB2Ni43NmwxNy4wNiAyLjgzdi01LjIzYS43Ni43NiAwIDAgMC0uNjQtLjc0ek01My40MyA1My42MmwxOC40MS0xLjEzYzIuMS02LjA1IDUuNTEtMTEuNzUgMTEtMTIuOGwtMTctMi4wOGMtNi42OCAxLjEyLTEwLjM2IDguMjktMTIuNDEgMTYuMDF6Ii8+PHBhdGggY2xhc3M9ImNscy02IiBkPSJNNDEuNzEgNTJsLjEzLS40NS0uMTMuNDZ6TTQxLjkxIDUxLjM0bC0uMDYuMjIuMDctLjIzek0yNy43MiA1NC42NmE2OC4yNiA2OC4yNiAwIDAgMC0uOTMgMTJ2Mi40MkwzOSA2Ni4xYTEuMDYgMS4wNiAwIDAgMCAuODEtMSA1OC43MiA1OC43MiAwIDAgMSAxLjY5LTEyLjI2YzAgLjE2LS4wOS4zMy0uMTMuNDl6TTY1Ljc4IDM0LjI4bC4wMSAzLjM0IDE3LjAzIDIuMDd2LTIuNThsLTE3LjA0LTIuODN6TTUwLjg3IDc0LjQ0TDY4IDY4LjY4YS45Mi45MiAwIDAgMCAuNjMtLjc5IDcyLjQ2IDcyLjQ2IDAgMCAxIDMuMTgtMTUuNGwtMTguMzggMS4xM2E5MC45MSA5MC45MSAwIDAgMC0yLjU2IDIwLjgyek01My40MyA1My42MnoiLz48L2c+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: kie-cloud-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: kie-cloud-operator
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
            type: RollingUpdate
          template:
            metadata:
              labels:
                name: kie-cloud-operator
            spec:
              containers:
              - command:
                - kie-cloud-operator
                env:
                - name: OPERATOR_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['name']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_UI
                  value: "true"
                - name: DEBUG
                  value: "false"
                - name: DM_KIESERVER_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.7.0
                - name: DM_CONTROLLER_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.7.0
                - name: DM_DC_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.7.0
                - name: PAM_KIESERVER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.7.0
                - name: PAM_CONTROLLER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.7.0
                - name: PAM_BC_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.7.0
                - name: PAM_BC_MONITORING_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.7.0
                - name: PAM_PROCESS_MIGRATION_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.7.0
                - name: PAM_SMARTROUTER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.7.0
                - name: OSE_CLI_IMAGE_7.7.0
                  value: registry.redhat.io/openshift3/ose-cli@sha256:7e356132f56fc4e3cf691ba5b0b5f063dc974c4cfe2f198c8c1b5f68cb9ccbdd
                - name: MYSQL_PROXY_IMAGE_7.7.0
                  value: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
                - name: POSTGRESQL_PROXY_IMAGE_7.7.0
                  value: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:de3ab628b403dc5eed986a7f392c34687bddafee7bdfccfd65cecf137ade3dfd
                - name: DATAGRID_IMAGE_7.7.0
                  value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:cfd8c4ac1c495b766dd3ff1a85c35afe092858f8f65b52a5b044811719482236
                - name: BROKER_IMAGE_7.7.0
                  value: registry.redhat.io/amq7/amq-broker@sha256:49adf926658cee75dafbb463cfc7b4f9a533d5f34c0e1622709263a5f64f8b1b
                - name: OAUTH_PROXY_IMAGE
                  value: registry.redhat.io/openshift3/oauth-proxy@sha256:cd284eeb883b549c4578a1a07b1ee58ccbd0c8b62c0678a981b5ed65a6cf1c16
                image: quay.io/kiegroup/kie-cloud-operator:1.4.0
                imagePullPolicy: Always
                name: kie-cloud-operator
                resources: {}
              serviceAccountName: kie-cloud-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          - apps
          - apps.openshift.io
          - rbac.authorization.k8s.io
          - route.openshift.io
          - build.openshift.io
          - image.openshift.io
          - app.kiegroup.org
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - kie-cloud-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - console.openshift.io
          resources:
          - consolelinks
          verbs:
          - get
          - create
          - update
          - delete
        serviceAccountName: kie-cloud-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kieapp
  - pam
  - decision
  - kie
  - cloud
  - bpm
  - process
  - automation
  - operator
  labels:
    alm-owner-kiecloud: kiecloud-operator
    operated-by: kiecloud-operator.1.4.0
  links:
  - name: Product Page
    url: https://access.redhat.com/products/red-hat-process-automation-manager
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/#category-deploying-red-hat-process-automation-manager-on-openshift
  maintainers:
  - email: bsig-cloud@redhat.com
    name: Red Hat, Inc.
  maturity: stable
  provider:
    name: Red Hat, Inc.
  relatedImages:
  - image: quay.io/kiegroup/kie-cloud-operator:1.4.0
    name: kie-cloud-operator
  - image: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8:7.7.0
    name: rhdm-kieserver-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-controller-rhel8:7.7.0
    name: rhdm-controller-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8:7.7.0
    name: rhdm-decisioncentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8:7.7.0
    name: rhpam-kieserver-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-controller-rhel8:7.7.0
    name: rhpam-controller-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8:7.7.0
    name: rhpam-businesscentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8:7.7.0
    name: rhpam-businesscentral-monitoring-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-process-migration-rhel8:7.7.0
    name: rhpam-process-migration-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8:7.7.0
    name: rhpam-smartrouter-rhel8
  - image: registry.redhat.io/openshift3/oauth-proxy@sha256:cd284eeb883b549c4578a1a07b1ee58ccbd0c8b62c0678a981b5ed65a6cf1c16
    name: oauth-proxy
  - image: registry.redhat.io/openshift3/ose-cli@sha256:7e356132f56fc4e3cf691ba5b0b5f063dc974c4cfe2f198c8c1b5f68cb9ccbdd
    name: ose-cli
  - image: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
    name: mysql-57-rhel7
  - image: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:de3ab628b403dc5eed986a7f392c34687bddafee7bdfccfd65cecf137ade3dfd
    name: postgresql-10-rhel7
  - image: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:cfd8c4ac1c495b766dd3ff1a85c35afe092858f8f65b52a5b044811719482236
    name: datagrid73-openshift
  - image: registry.redhat.io/amq7/amq-broker@sha256:49adf926658cee75dafbb463cfc7b4f9a533d5f34c0e1622709263a5f64f8b1b
    name: amq-broker
  replaces: kiecloud-operator.1.3.0
  selector:
    matchLabels:
      alm-owner-kiecloud: kiecloud-operator
      operated-by: kiecloud-operator.1.4.0
  version: 1.4.0
