## KIE ProcessMigration BEGIN
processMigration:
  ## KIE ProcessMigration ConfigMap BEGIN
  configMaps:
    - metadata:
        name: "[[.ApplicationName]]-process-migration"
      data:
        project-overrides.yml: |-
          kieservers:
            #[[range $index, $Map := .ProcessMigration.KieServerClients]]
            - host: [[.Host]]
              username: [[.Username]]
              password: [[.Password]]
            #[[end]]
          thorntail:
            datasources:
              data-sources:
                pimDS:
                  driver-name: "[[.ProcessMigration.Database.ExternalConfig.Driver]]"
                  connection-url: "[[.ProcessMigration.Database.ExternalConfig.JdbcURL]]"
                  user-name: "[[.ProcessMigration.Database.ExternalConfig.Username]]"
                  password: "[[.ProcessMigration.Database.ExternalConfig.Password]]"
                  #[[if .ProcessMigration.Database.ExternalConfig.MaxPoolSize]]
                  max-pool-size: "[[.ProcessMigration.Database.ExternalConfig.MaxPoolSize]]"
                  #[[end]]
                  #[[if .ProcessMigration.Database.ExternalConfig.MinPoolSize]]
                  min-pool-size: "[[.ProcessMigration.Database.ExternalConfig.MinPoolSize]]"
                  #[[end]]
                  #[[if .ProcessMigration.Database.ExternalConfig.ConnectionChecker]]
                  valid-connection-checker-class-name: "[[.ProcessMigration.Database.ExternalConfig.ConnectionChecker]]"
                  #[[end]]
                  #[[if .ProcessMigration.Database.ExternalConfig.ExceptionSorter]]
                  exception-sorter-class-name: "[[.ProcessMigration.Database.ExternalConfig.ExceptionSorter]]"
                  #[[end]]
                  #[[if .ProcessMigration.Database.ExternalConfig.BackgroundValidation]]
                  background-validation: "[[.ProcessMigration.Database.ExternalConfig.BackgroundValidation]]"
                  #[[end]]
                  #[[if .ProcessMigration.Database.ExternalConfig.BackgroundValidationMillis]]
                  background-validation-millis: "[[.ProcessMigration.Database.ExternalConfig.BackgroundValidationMillis]]"
                  #[[end]]
  ## KIE ProcessMigration ConfigMap END
## KIE ProcessMigration END
