console:
  deploymentConfigs:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]"
      spec:
        template:
          spec:
            containers:
              - name: "[[.ApplicationName]]-[[.Console.Name]]"
                env:
                  - name: KIE_SERVER_HOST
                  - name: JGROUPS_PING_PROTOCOL
                  - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                  - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            volumes:
              - name: "[[.ApplicationName]]-[[.Console.Name]]-pvol"
                emptyDir: {}
  persistentVolumeClaims:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-claim"
        annotations:
          delete: "true"
  services:
    - metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-ping"
        annotations:
          delete: "true"
  routes:
    - id: "[[.ApplicationName]]-[[.Console.Name]]-http"
      metadata:
        name: "[[.ApplicationName]]-[[.Console.Name]]-http"
        labels:
          app: "[[.ApplicationName]]"
          application: "[[.ApplicationName]]"
          service: "[[.ApplicationName]]-[[.Console.Name]]"
        annotations:
          description: Route for Business Central's http service.
          haproxy.router.openshift.io/timeout: 60s
      spec:
        to:
          name: "[[.ApplicationName]]-[[.Console.Name]]"
        port:
          targetPort: http
## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            metadata:
              name: "[[.KieName]]"
            spec:
              containers:
                - name: "[[.KieName]]"
                  env:
                    - name: JGROUPS_PING_PROTOCOL
                    - name: OPENSHIFT_DNS_PING_SERVICE_NAME
                    - name: OPENSHIFT_DNS_PING_SERVICE_PORT
                    - name: FILTERS
                      value: "AC_ALLOW_ORIGIN,AC_ALLOW_METHODS,AC_ALLOW_HEADERS,AC_ALLOW_CREDENTIALS,AC_MAX_AGE"
                    - name: AC_ALLOW_ORIGIN_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Origin"
                    - name: AC_ALLOW_ORIGIN_FILTER_RESPONSE_HEADER_VALUE
                      value: "*"
                    - name: AC_ALLOW_METHODS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Methods"
                    - name: AC_ALLOW_METHODS_FILTER_RESPONSE_HEADER_VALUE
                      value: "GET, POST, OPTIONS, PUT"
                    - name: AC_ALLOW_HEADERS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Headers"
                    - name: AC_ALLOW_HEADERS_FILTER_RESPONSE_HEADER_VALUE
                      value: "Accept, Authorization, Content-Type, X-Requested-With"
                    - name: AC_ALLOW_CREDENTIALS_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Allow-Credentials"
                    - name: AC_ALLOW_CREDENTIALS_FILTER_RESPONSE_HEADER_VALUE
                      value: "true"
                    - name: AC_MAX_AGE_FILTER_RESPONSE_HEADER_NAME
                      value: "Access-Control-Max-Age"
                    - name: AC_MAX_AGE_FILTER_RESPONSE_HEADER_VALUE
                      value: "1"
    ## KIE server deployment config END
    ## KIE server route BEGIN
    routes:
      - id: "[[.KieName]]-http"
        metadata:
          name: "[[.KieName]]-http"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
          annotations:
            description: Route for KIE server's http service.
            haproxy.router.openshift.io/balance: source
            haproxy.router.openshift.io/timeout: 60s
        spec:
          to:
            name: "[[.KieName]]"
          port:
            targetPort: http
    ## KIE server route END
#[[end]]
## RANGE ends
## KIE Servers END
