apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-production-immutable-jms
  annotations:
    consoleName: rhpam-production-immutable-jms
    consoleTitle: PAM Production Immutable JMS
    consoleDesc: Deploys a PAM Production Immutable JMS environment
spec:
  environment: rhpam-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhpam-kieserver-library=org.openshift.quickstarts:rhpam-kieserver-library:1.6.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhpam-7-openshift-image.git
            reference: main
            contextDir: quickstarts/library-process/library
        jms:
          enableIntegration: true
          enableSignal: true
          enableAudit: true
          # To be able to connect on the AMQ outside OpenShift, SSL needs to be configued
          # it will only be configured if all the next 5 parameters are set.
          # About how to configure the AMQ to support ssl, please visit:
          # https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/deploying_amq_broker_on_openshift_container_platform/configure-ssl-broker-ocp#configuring-ssl_broker-ocp
          # amqSecretName: broker-secret
          # amqTruststoreName: broker.ts
          # amqTruststorePassword: "123456"
          # amqKeystoreName: broker.ks
          # amqKeystorePassword: "123456"
