apiVersion: app.kiegroup.org/v1
kind: KieApp
metadata:
  name: rhpam-production-immutable-jms
spec:
  environment: rhpam-production-immutable
  objects:
    servers:
      - build:
          kieServerContainerDeployment: rhpam-kieserver-library=org.openshift.quickstarts:rhpam-kieserver-library:1.5.0-SNAPSHOT
          gitSource:
            uri: https://github.com/jboss-container-images/rhpam-7-openshift-image.git
            reference: master
            contextDir: quickstarts/library-process/library
        jms:
          enableIntegration: true
          enableSignal: true
          enableAudit: true
