## KIE Servers BEGIN
servers:
  ## RANGE BEGINS
  #[[ range $index, $Map := .Servers ]]
  - deploymentConfigs:
      ## KIE server deployment config BEGIN
      - metadata:
          name: "[[.KieName]]"
        spec:
          template:
            metadata:
              name: "[[.KieName]]"
            spec:
              containers:
                - name: "[[.KieName]]"
                  env:
                    ## H2 driver settings BEGIN
                    - name: DATASOURCES
                      value: "RHPAM"
                    - name: RHPAM_DATABASE
                      value: "rhpam7"
                    - name: RHPAM_JNDI
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_JTA
                      value: "true"
                    - name: RHPAM_DRIVER
                      value: "h2"
                    - name: KIE_SERVER_PERSISTENCE_DIALECT
                      value: "org.hibernate.dialect.H2Dialect"
                    - name: RHPAM_USERNAME
                      value: "rhpam"
                    - name: RHPAM_PASSWORD
                      value: "[[$.DBPassword]]"
                    - name: RHPAM_SERVICE_HOST
                      value: "dummy_ignored"
                    - name: RHPAM_SERVICE_PORT
                      value: "12345"
                    - name: KIE_SERVER_PERSISTENCE_DS
                      value: "java:/jboss/datasources/rhpam"
                    - name: RHPAM_NONXA
                      value: "false"
                    - name: RHPAM_XA_CONNECTION_PROPERTY_URL
                      value: "jdbc:h2:/opt/kie/data/h2/rhpam;AUTO_SERVER=TRUE"
                    ## H2 driver settings END
                  volumeMounts:
                    - name: "[[.KieName]]-kie-[[$.Constants.DatabaseVolumeSuffix]]"
                      mountPath: "/opt/kie/data"
              ## [[ if ne .Database.Size "" ]]
              volumes:
                ## H2 volume settings BEGIN
                - name: "[[.KieName]]-kie-[[$.Constants.DatabaseVolumeSuffix]]"
                  persistentVolumeClaim:
                    claimName: "[[.KieName]]-kie-claim"
    ## KIE server deployment config END
    persistentVolumeClaims:
      ## H2 persistent volume claim BEGIN
      - metadata:
          name: "[[.KieName]]-kie-claim"
          labels:
            app: "[[$.ApplicationName]]"
            application: "[[$.ApplicationName]]"
            service: "[[.KieName]]"
        spec:
          # [[ if ne .Database.StorageClassName "" ]]
          storageClassName: "[[.Database.StorageClassName]]"
          # [[ end ]]
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: "[[.Database.Size]]"
              ## H2 persistent volume claim END
              ## [[ else ]]
              volumes:
                ## H2 volume settings BEGIN
                - name: "[[.KieName]]-kie-[[$.Constants.DatabaseVolumeSuffix]]"
                  emptyDir: {}
## [[ end ]]
#[[end]]
## RANGE ends
## KIE Servers END
