apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"app.kiegroup.org/v2","kind":"KieApp","metadata":{"name":"rhpam-trial"},"spec":{"environment":"rhpam-trial"}}]'
    capabilities: Seamless Upgrades
    categories: Integration & Delivery
    certified: "true"
    containerImage: registry.redhat.io/rhpam-7/rhpam-rhel8-operator@sha256:6ac3d491e2753f7b075c1f5600ef44233c5597ea677cb667f5d5c10f97bfd1b6
    createdAt: "2020-05-26 17:14:49"
    description: Deploys and manages Red Hat Process Automation Manager and Red Hat
      Decision Manager environments.
    repository: https://github.com/kiegroup/kie-cloud-operator
    support: Red Hat
    tectonic-visibility: ocs
  labels:
    operator-businessautomation: "true"
    operatorframework.io/arch.amd64: supported
    operatorframework.io/os.linux: supported
  name: businessautomation-operator.1.4.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: A project prescription running an RHPAM/RHDM environment.
      displayName: KieApp
      kind: KieApp
      name: kieapps.app.kiegroup.org
      resources:
      - kind: DeploymentConfig
        name: ""
        version: apps.openshift.io/v1
      - kind: StatefulSet
        name: ""
        version: apps/v1
      - kind: Role
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: RoleBinding
        name: ""
        version: rbac.authorization.k8s.io/v1
      - kind: Route
        name: ""
        version: route.openshift.io/v1
      - kind: BuildConfig
        name: ""
        version: build.openshift.io/v1
      - kind: ImageStream
        name: ""
        version: image.openshift.io/v1
      - kind: Secret
        name: ""
        version: v1
      - kind: PersistentVolumeClaim
        name: ""
        version: v1
      - kind: ServiceAccount
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: Set true to enable automatic micro version product upgrades,
          it is disabled by default.
        displayName: Enable Upgrades
        path: upgrades.enabled
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Set true to enable automatic minor product version upgrades,
          it is disabled by default. Requires spec.upgrades.enabled to be true.
        displayName: Include minor version upgrades
        path: upgrades.minor
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Set true to enable image tags, disabled by default. This will
          leverage image tags instead of the image digests.
        displayName: Use Image Tags
        path: useImageTags
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: Environment deployed.
        displayName: Environment
        path: environment
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Product version installed.
        displayName: Version
        path: version
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      statusDescriptors:
      - description: Deployments for the KieApp environment.
        displayName: Deployments
        path: deployments
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podStatuses
      - description: Current phase.
        displayName: Status
        path: phase
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: The address for accessing Business Central, if it is deployed.
        displayName: Business/Decision Central URL
        path: consoleHost
        x-descriptors:
        - urn:alm:descriptor:org.w3:link
      version: v2
  description: |-
    Deploys and manages Red Hat Process Automation Manager and Red Hat Decision Manager environments.

    * **Red Hat Process Automation Manager** is a platform for developing containerized microservices and applications that automate business decisions and processes. It includes business process management (BPM), business rules management (BRM), and business resource optimization and complex event processing (CEP) technologies. It also includes a user experience platform to create engaging user interfaces for process and decision services with minimal coding.

     * **Red Hat Decision Manager** is a platform for developing containerized microservices and applications that automate business decisions. It includes business rules management, complex event processing, and resource optimization technologies. Organizations can incorporate sophisticated decision logic into line-of-business applications and quickly update underlying business rules as market conditions change.

    [See more](https://www.redhat.com/en/products/process-automation).
  displayName: Business Automation
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MjEuMTUgNzIxLjE1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2RkMzkyNjt9LmNscy0ye2ZpbGw6I2NjMzQyNzt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2U1ZTVlNDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlByb2R1Y3RfSWNvbi1SZWRfSGF0LUF1dG9tYXRpb24tUkdCPC90aXRsZT48Y2lyY2xlIGNsYXNzPSJjbHMtMSIgY3g9IjM2MC41NyIgY3k9IjM2MC41NyIgcj0iMzU4LjU4Ii8+PHBhdGggY2xhc3M9ImNscy0yIiBkPSJNNjEzLjc4LDEwNy4wOSwxMDYuNzIsNjE0LjE2YzE0MC4xNCwxMzguNjIsMzY2LjExLDEzOC4xNiw1MDUuNjctMS40Uzc1Mi40LDI0Ny4yNCw2MTMuNzgsMTA3LjA5WiIvPjxwb2x5Z29uIGNsYXNzPSJjbHMtMyIgcG9pbnRzPSIzNzguOTcgMzI3LjQ4IDQ2MS43NyAxNTkuNTcgMjU5LjY3IDE1OS40OSAyNTkuNjcgNDEzLjEgMzA2Ljk3IDQxMy43OCAzOTMuMjcgMzI3LjQ3IDM3OC45NyAzMjcuNDgiLz48cG9seWdvbiBjbGFzcz0iY2xzLTQiIHBvaW50cz0iMzU5LjYgNTc4LjA2IDQ4Mi41NSAzMjcuNDUgMzkzLjI3IDMyNy40NyAzMDYuOTcgNDEzLjc4IDM1OS42IDQxNC41MiAzNTkuNiA1NzguMDYiLz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments:
      - name: business-automation-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: business-automation-operator
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
            type: RollingUpdate
          template:
            metadata:
              labels:
                name: business-automation-operator
            spec:
              containers:
              - command:
                - kie-cloud-operator
                env:
                - name: OPERATOR_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['name']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_UI
                  value: "true"
                - name: DEBUG
                  value: "false"
                - name: DM_KIESERVER_IMAGE_7.7.1
                  value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8@sha256:16461e4b59424965608a2bd0519525e33468dbacdeb32aac44bf77d81419f04d
                - name: DM_CONTROLLER_IMAGE_7.7.1
                  value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8@sha256:05c2d24caaf28f50527d8f710cec03960360be50b89fd9a6e5b40d239c18f5ca
                - name: DM_DC_IMAGE_7.7.1
                  value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8@sha256:39afa1dcb5634bbe4901c0ed36d66b92713e8101ffa5ea9f20b94d9d93de9b5f
                - name: PAM_KIESERVER_IMAGE_7.7.1
                  value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8@sha256:071d0add5cbcf5ba06b3f87034a0dc8d80590ae7efc13f6fafaee63bc54dc090
                - name: PAM_CONTROLLER_IMAGE_7.7.1
                  value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8@sha256:b731ec8d1d87a24711b525aaf254ee15d701b60003b97199a097e09d96571666
                - name: PAM_BC_IMAGE_7.7.1
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8@sha256:8eeaa8b6ef049bad0aba252eebad45ca704b97d638a4a789899000b2143b8f11
                - name: PAM_BC_MONITORING_IMAGE_7.7.1
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8@sha256:db84958e32e5857c60d088f3866665c4405234a961f571b91161f31eb3d35cca
                - name: PAM_SMARTROUTER_IMAGE_7.7.1
                  value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8@sha256:d0d426173e6e3fed9747147e34d19388611815bc93f38dd6f5b3c2f2bd6cc0cd
                - name: OSE_CLI_IMAGE_7.7.1
                  value: registry.redhat.io/openshift3/ose-cli@sha256:eda798d5c0f026b2221716f5df33fd97cd25bfb565f969e76e62815f1bd3a924
                - name: MYSQL_PROXY_IMAGE_7.7.1
                  value: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
                - name: POSTGRESQL_PROXY_IMAGE_7.7.1
                  value: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:5c4f5f52a37718a9a1997ba212ef172694475558c35232b56dac638529c5b569
                - name: DATAGRID_IMAGE_7.7.1
                  value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:3375ec169d274278da56d1401c5c1285f7d2812ea0bde2ac9ad9652b69f80893
                - name: BROKER_IMAGE_7.7.1
                  value: registry.redhat.io/amq7/amq-broker@sha256:ba5273b390a4762c21f005fdc92a837680417250dcd5e6d9d3c8f776e9cc372e
                - name: DM_KIESERVER_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8@sha256:debf4f45f36509e608c2d8754539aa5697aa4255ac85ab4a521915ef88841660
                - name: DM_CONTROLLER_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-controller-rhel8@sha256:92542ad2b83f42eb0f245daa1e732c752d9c164f31fb963f42ac876aeba42c98
                - name: DM_DC_IMAGE_7.7.0
                  value: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8@sha256:be1c8fca841bffd7d63bb8522bb7a7b35d18acd36e1cd8e576ea111d9f9e48f1
                - name: PAM_KIESERVER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8@sha256:75372031305a597171895641edf46f19664d08bea19d9c41e6d8d43042a3c97d
                - name: PAM_CONTROLLER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-controller-rhel8@sha256:05f7956bcae5acd10e89ecbbc5a12b9bd737cf696c276bb10f52bd93b8080ebd
                - name: PAM_BC_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8@sha256:43674501114fe87ad692b3dcc00e0c3c8a98cef0876c0b70051904c0330d5152
                - name: PAM_BC_MONITORING_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8@sha256:f236fb93165f83b88a9edda70f05fe9eaab2f6f3838f18eead2c1cd8318c03d9
                - name: PAM_SMARTROUTER_IMAGE_7.7.0
                  value: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8@sha256:4fbfe67e9b7d8411ef963815d2c2bbbd8071025741f8f0184d48b5bd769dc9e3
                - name: OSE_CLI_IMAGE_7.7.0
                  value: registry.redhat.io/openshift3/ose-cli@sha256:eda798d5c0f026b2221716f5df33fd97cd25bfb565f969e76e62815f1bd3a924
                - name: MYSQL_PROXY_IMAGE_7.7.0
                  value: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
                - name: POSTGRESQL_PROXY_IMAGE_7.7.0
                  value: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:5c4f5f52a37718a9a1997ba212ef172694475558c35232b56dac638529c5b569
                - name: DATAGRID_IMAGE_7.7.0
                  value: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:cfd8c4ac1c495b766dd3ff1a85c35afe092858f8f65b52a5b044811719482236
                - name: BROKER_IMAGE_7.7.0
                  value: registry.redhat.io/amq7/amq-broker@sha256:ba5273b390a4762c21f005fdc92a837680417250dcd5e6d9d3c8f776e9cc372e
                - name: OAUTH_PROXY_IMAGE
                  value: registry.redhat.io/openshift3/oauth-proxy@sha256:4a5d0a92b80ab0738c0a3e3c975a7c59a4242d4337def418bec7f9ec77785ada
                image: registry.redhat.io/rhpam-7/rhpam-rhel8-operator@sha256:6ac3d491e2753f7b075c1f5600ef44233c5597ea677cb667f5d5c10f97bfd1b6
                imagePullPolicy: Always
                name: business-automation-operator
                resources: {}
              serviceAccountName: business-automation-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          - apps
          - apps.openshift.io
          - rbac.authorization.k8s.io
          - route.openshift.io
          - build.openshift.io
          - image.openshift.io
          - app.kiegroup.org
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - operators.coreos.com
          resources:
          - clusterserviceversions
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - business-automation-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        serviceAccountName: business-automation-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - kieapp
  - pam
  - decision
  - kie
  - cloud
  - bpm
  - process
  - automation
  - operator
  labels:
    alm-owner-businessautomation: businessautomation-operator
    operated-by: businessautomation-operator.1.4.1
  links:
  - name: Product Page
    url: https://access.redhat.com/products/red-hat-process-automation-manager
  - name: Documentation
    url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.7/#category-deploying-red-hat-process-automation-manager-on-openshift
  maintainers:
  - email: bsig-cloud@redhat.com
    name: Red Hat
  maturity: stable
  provider:
    name: Red Hat
  relatedImages:
  - image: registry.redhat.io/rhpam-7/rhpam-rhel8-operator@sha256:6ac3d491e2753f7b075c1f5600ef44233c5597ea677cb667f5d5c10f97bfd1b6
    name: rhpam-rhel8-operator
  - image: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8@sha256:16461e4b59424965608a2bd0519525e33468dbacdeb32aac44bf77d81419f04d
    name: rhdm-kieserver-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-controller-rhel8@sha256:05c2d24caaf28f50527d8f710cec03960360be50b89fd9a6e5b40d239c18f5ca
    name: rhdm-controller-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8@sha256:39afa1dcb5634bbe4901c0ed36d66b92713e8101ffa5ea9f20b94d9d93de9b5f
    name: rhdm-decisioncentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8@sha256:071d0add5cbcf5ba06b3f87034a0dc8d80590ae7efc13f6fafaee63bc54dc090
    name: rhpam-kieserver-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-controller-rhel8@sha256:b731ec8d1d87a24711b525aaf254ee15d701b60003b97199a097e09d96571666
    name: rhpam-controller-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8@sha256:8eeaa8b6ef049bad0aba252eebad45ca704b97d638a4a789899000b2143b8f11
    name: rhpam-businesscentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8@sha256:db84958e32e5857c60d088f3866665c4405234a961f571b91161f31eb3d35cca
    name: rhpam-businesscentral-monitoring-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8@sha256:d0d426173e6e3fed9747147e34d19388611815bc93f38dd6f5b3c2f2bd6cc0cd
    name: rhpam-smartrouter-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-kieserver-rhel8@sha256:debf4f45f36509e608c2d8754539aa5697aa4255ac85ab4a521915ef88841660
    name: rhdm-kieserver-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-controller-rhel8@sha256:92542ad2b83f42eb0f245daa1e732c752d9c164f31fb963f42ac876aeba42c98
    name: rhdm-controller-rhel8
  - image: registry.redhat.io/rhdm-7/rhdm-decisioncentral-rhel8@sha256:be1c8fca841bffd7d63bb8522bb7a7b35d18acd36e1cd8e576ea111d9f9e48f1
    name: rhdm-decisioncentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-kieserver-rhel8@sha256:75372031305a597171895641edf46f19664d08bea19d9c41e6d8d43042a3c97d
    name: rhpam-kieserver-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-controller-rhel8@sha256:05f7956bcae5acd10e89ecbbc5a12b9bd737cf696c276bb10f52bd93b8080ebd
    name: rhpam-controller-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-rhel8@sha256:43674501114fe87ad692b3dcc00e0c3c8a98cef0876c0b70051904c0330d5152
    name: rhpam-businesscentral-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-businesscentral-monitoring-rhel8@sha256:f236fb93165f83b88a9edda70f05fe9eaab2f6f3838f18eead2c1cd8318c03d9
    name: rhpam-businesscentral-monitoring-rhel8
  - image: registry.redhat.io/rhpam-7/rhpam-smartrouter-rhel8@sha256:4fbfe67e9b7d8411ef963815d2c2bbbd8071025741f8f0184d48b5bd769dc9e3
    name: rhpam-smartrouter-rhel8
  - image: registry.redhat.io/openshift3/oauth-proxy@sha256:4a5d0a92b80ab0738c0a3e3c975a7c59a4242d4337def418bec7f9ec77785ada
    name: oauth-proxy
  - image: registry.redhat.io/openshift3/ose-cli@sha256:eda798d5c0f026b2221716f5df33fd97cd25bfb565f969e76e62815f1bd3a924
    name: ose-cli
  - image: registry.redhat.io/rhscl/mysql-57-rhel7@sha256:9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe
    name: mysql-57-rhel7
  - image: registry.redhat.io/rhscl/postgresql-10-rhel7@sha256:5c4f5f52a37718a9a1997ba212ef172694475558c35232b56dac638529c5b569
    name: postgresql-10-rhel7
  - image: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:cfd8c4ac1c495b766dd3ff1a85c35afe092858f8f65b52a5b044811719482236
    name: datagrid73-openshift
  - image: registry.redhat.io/jboss-datagrid-7/datagrid73-openshift@sha256:3375ec169d274278da56d1401c5c1285f7d2812ea0bde2ac9ad9652b69f80893
    name: datagrid73-openshift
  - image: registry.redhat.io/amq7/amq-broker@sha256:ba5273b390a4762c21f005fdc92a837680417250dcd5e6d9d3c8f776e9cc372e
    name: amq-broker
  replaces: businessautomation-operator.1.4.0
  selector:
    matchLabels:
      alm-owner-businessautomation: businessautomation-operator
      operated-by: businessautomation-operator.1.4.1
  version: 1.4.1
