apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: kiecloud-operator.v0.1.0
  namespace: placeholder
  annotations:
    categories: kieapp, rhpam, kie, cloud, pam, bpm, process, case, automation, operator
    certified: "false"
    description: KieCloud can deploy RHPAM environments in the form of KieApp objects.
    containerImage: quay.io/kiegroup/kie-cloud-operator:0.1
    createdAt: 2019-01-25T20:48:22Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{"apiVersion":"app.kiegroup.org/v1","kind":"KieApp","metadata":{"name":"trial"},"spec":{"environment":"trial"}}]
  labels:
    operator-kiecloud: "true"
spec:
  displayName: KieCloud
  description: KieCloud can deploy RHPAM environments in the form of KieApp objects.
  keywords: [kieapp rhpam kie cloud pam bpm process case automation operator]
  version: 0.1.0
  maturity: beta
  maintainers:
    - name: Red Hat, Inc.
      email: bsig-cloud@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-process-automation-manager
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_process_automation_manager/7.2/html-single/installing_and_configuring_red_hat_process_automation_manager_on_red_hat_jboss_eap_7.2/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAIIAAABlCAYAAACBQjvHAAAABHNCSVQICAgIfAhkiAAAFsJJREFUeJztnXd0XNWdx3/3vTe9qI1GGvUuI9mSJfcKbuACGBNCSSXJ2c1uzklI25yzm+QkgU1C2pLdUFL2AEkgIWAvxRgMBhthG9yRbclFlq0ykkbSaHp98967v/1jVEGSPZonWxrN5xydGc27c9+99/d9v9vvACRJkiRJkiRJknwScqMTMIdREAAOCHAAhGEIKDmG0Rs0imyjWpHmDPA2dzDSBADC9UhMUgjywgCAgiFEpVJw6dlp+vzS7PQilYLVEQAVxxBjmk5VWFecveim3LQCoEgAEQAoQYqEoEQYAI4BykgSFbscPtveJuvLjVbnO6393hMiRdd0JTwphNhRKDg2JcOoy87JSLEoONaoUynzqwuzltSX5s7TKBVqgpRlGaLRKxXGVJ3KwDHAIqUAQAGQAtLoKyACIAKiBDD0GR36fDAsSuAM8F6HN2Tbfbpzz7le71uX7f4zIUHqAwCUK1NJIYwPIYQoVQpOa9RpUpUKzpRh1FUsqihaWl1kKVOybJo5TZ9fYE7NVrIM9wkDUgo4aORhg8YhBEAcvu4N88ELNu+5o+2OhkOt9lf6fHxzWKReAJDiyrA85TarIYQQhmUYjU6jKqmrKFpdV1lcrVersrLSDKULyvIrjWqVJmoUBKDSKAOOGPd6CQFHhUGU4MMrjlPn+ryH9jT3v2j3R05KiOEpFYK8ZTorYDiWTbNkplcvriqry0jRl84rzF22qnbeQq1SocRRhkCgHzPCzBNCNFw0zMU+X+e7lxw7D7W5d3e6w8coQvBaCyXRhcBwLJuSmZ5aPL+8qCbHlL7olsU1a/OyMrKUClan16q1HAAzxiizWAhD9/CGBH+fN9Szq2ngueNW3+u9fuEsAIiTFVRCCYEQojLqdWaLOaOwINu8Yt2yhWtyzabcFIM2uzA7y8IQJDiqUAFGvR9PCB8LM64QhsQwiRCGDR+3ECQYSf/EQojGI4EkUdrlCdk+6vYffuGs84kub+RDxPG7o9x1tJPcEJZhlFqtxmjUacvWLFm4ub66si43yzSvuqyolCWEGSlMHC702O4AV2+XX0MYQmK/9ZRvNupGLEOYwlRVbqFRca+WI+ZHD/Z+npewa7yvzUYhKMym9LpNa5bfWpSXU7d6ce3a/KxMEwAOPzk49LTNZq5FYFcPAgAAR6z+E09/5PgRL6FtojAzXgiEEFV6akrFsrqaFQV5lsVbblm1JT8n28wxRMEAISMu98alkSIBikzU8wABCgxIgADDfxSA4HD1QAkAAgUGov8jIABDgaAESgwDQbym/IwbZJT7ae4LXtzVZP/TO63eJ67Wm5iJQmC0Gk3WvLKS2sqy4lt2bLt1q1GnNWWb0jMVHMt9oi6XAQrRqCQKQCkBijj4SkCgBBAJCJQFiggS5UBCAogIwuDtETFqlMH0DP8PONgKw0EhRN9H7YxRgw+FG8yXggqgk3ygkQKgEkPADrVTrhEfL4ZOdXmP7m4eeO58f3CfOyxaryWCGSEEjuP0mab0nMyMjPlbNty8vaaqsm5eWXGFRqVSjTTchp6oawcRgSIApTj8J0gUBImCKFEQKEKEIlAKQBFAotERX4pM9HvIDkUElFIMhoLBQDDkoRLlMZooGLbuYLiR19HvCRkyNiHAsgyj0mrUKRqVSsMwJHpTAgAEQSIshFk1EMwApcSDSgqCVvSCRvADS3kgE5jUGRTdJ6yu47tO9z1+vj/wnkjRG5MNYipZGSGEMGq1Km/jLWvvWbVs0frli+pWZZkyUmMxPI5+g1Ej84IIEVECXqAgSBKIlEJElFAQJSpEH3UcfloRoMvWa2s613LC6/O2iaLoRgQJonWNNHgDEQEppVTqtvV1W3tsF8J8ZAARR7e+r/bYskNvGIao1EqVKc9irswxm3IYhuEIAAOALETlwAIAyxCi0qpVecW52XWVxQWVGjVyGtEHetFDtBEPcMgToAh2P+/Z09y7s+Gy88VWe+AgAkRiMsQg17v7yGaaMhZsXLd2a33tgttuv+3WtQBD3bHBen50Vw1HulI42F2LRATgRQkighg1ekREXpIIL0jAi6LY2nrlcld39zme53spRZ4Aih6fz914pvm4w+VuiRobIxAdkhUgasSZDgPRh5YjhKiVHJeeplMVAhVpny98FGMYOJqIaRcCwzCaHIulalFd7S3bbtv06eqqygqjQW9UsCyLFGGMECgOuuGooQVRAD4iQjgiQIgXwO50+TutXe0+n79bkqRgd29vz9mmc8cdLtc5KkkeihgOh8P+SEQIUkoFgDEttiSTMC1VA8uy+uKiwpvmVVasu3vH9rsK83JK8ywWc7ShNDKQAoDRuloUQYwIEAzz2GPr8/YNDPSFQmGP3eFyHj1+4vCAw9EkSZIjGAp5XC63ned556BrjmuiJckIsgmBZVlVampq3pJF9du2bd28rW5hzTKzyZQyNPqGFAEpgkQphEIhyeFwhbyBAO/xeIJHjp04daWt40QkEunusfVabb22Szwf6cdolyf5NF8H4hYCwzDaysrKjZ954L4Hb9+2ZYtOq1Uj0sG+MIIgiBgMBYnD6Yq813Dw6OUr7Sf67PYr586dP+VyuS5SSj1wlXHwJNPPlNoIhBBlaWnpyjVr19xx1/btd5eVleRxLMMSABIOh8FuHwidOHnirNXaffHY8RNHL1y4eDgcDreLohiglIqQfMpnHLEIgdFqtZbq+fNvvvf+ex9cs2r10pTUFIPb6Qxfar3Ubu20tjU0vH/k0qXWD/1+f6fH4xmIRCI+SD7ts4KrCoEQotRoNJai4qLVGzZuunP9hg1LqSSFPzh8qKm5ufmo1Wo9097W3hIMBnsGu2WTwQz+ASFAogMt44M4PIggQdKDTDuTCYFTqVR5ZrN5kTkrqxwAwoFAoHPAbm93uVztkiS54BoMRAhhDHp9/qoVyz61cvmSWgaIAgEZgpQQABZGjRfgyJgBAqUSRUo9Hq97/wfHDre2Wxv8wVAvIiY9zDQwkRA4juMsCoVCj4gCz/M9iBjzoAXHccbPPnDf9778xc9+LdtkSsPBefKRef3B+Xc6et5dGp6vRyoNz8O73B7frjf3v/ziG+8+2dM/cAySXkJWJvMI1zrLOS4pKcaCf//ed/9w5x1bN7EEWJCGVtdMJoTB9+MIASgFSiUMBkKhF/bs2/Xim/sf6+l3NMaTxiQjsFcPEjsGgyH3xz/8/l+2bt28nmMYdnh2bfgVxv6PowYAEce/hggECFFwrKL+prLapQsqN7m9PrHTZr9AKZ3S+HqSEWQXglqtTv/Ot7/5xKfvuXsbS4AZY+A4hTD8PUTISDWmrVm0YENeVkZ944XLR8J8xC13XuYScguBueuu7Q9951sPfX1cA19VCHDNQgBAULAMV1mYV7G8Zt7tJ5ovNrp9gQ6Z8zNnkFUIVVVVtz788E9+bdDrtKMNhogQDIbA6faAy+sHry8AFy61dn5w9FhDUV5OgVKhUMTqEUZfN6UY0tctWbD9UkePrbvfcVbOPM0VZBOCUqlMe+SRh/+4YH51xZCREBH8gQBYe3qh1z4AHl8ABhzO0Cu79zz/28d//+C+Awf/smffgV0UqaYw11KiUQ8tRIlNCIAIeo1Ks7CyeEVrZ7et2+5skitfcwXZhLBjx46HvvCFz32OZaONQypJ0GcfAGuPDUKhMCBSCIVD4b///R+/3vPG3h+EQqF+RBS8Pn//keOn9p46c+5MTfW8FakGQwoBILEKAQAhRafR11eWrG7p7O7psbuaIdmjuGZkEYJKrc567LH/ejYjPT0FAEGSJOjs7ob+/gGgNDpAKIqi9MILLz62/8B7j0iSNGZMAhElW7/94v5DR94qyc9blpeTbWEIkFiFAIBg1Gp0K+aXrz/T0n6p3+W9BLNj4ckNRw4hMPc/cP+/3XHH7VsYQgilFLp7bGAfGBg2HkWK7757YNfLr7z6dUopP1FEgWBw4PDxU/sKci1LSgvzC6YiBEAEnVqlXja/fOP59q4O24CrWYY8JjxxC8FgMGT/7NFH/5ienmZAROjv7webbeyO7fPnL5x58qnf3ytJkv9q8YX5iPvIydPvmE3pCypKCkumIoShNsPy6rJ1l7t7+7v6nafjzWeiE7cQbtu8+Z/uf+D+TwEgeD0e6OrqBkpHFg653W7X008/+0273f7RtcbJRyLeM+dbjhbkWhYX5+XkT0UIgAh6tVJTU5a/rK2nv7/L7joTb14TGSaeL6vV6ow77rrrbgAAURShu7sHRGFkTohSSl9/fc//trS07Ik17n6Hs+Xh//7DV7r77f3xpDE/MyP7J1/51G8XlhfcQ0h8+U1k4iqY8ory+iVLlywGAOi32yEYDI25fuVK24WDBw89PtUZQ7vDdf6Hv3ri2z5/MBBPOs1phrRHvrzjcUtG6pJ44klk4hECc98Dn/mqQa9X8zwPfb19nwiwc+fOX/h8vs447gHHTjc//9Tzu54QJSmuhaq5mWnm33ztvr9mpRmr4oknUZmyENLS0soWLVm8CBGht7cPPm6n042nj1282LI77hQCwIt79v1y/4cnG+KNpzw3q+xf77z5VxqVwiRHuhKJKQth5erV64uKivP4CA9Op2PMNUEQhTfeePN/eJ6X5RSwMB9xPPX8rh919fZPuJt3NDjBOBLDALltSfWmz21c+gghRClH2hKFKQth6fLlWzmFgnMMOEASxzYBWltbLzQ1Ne2MO3WjuNRu/fB3f3npN9LQCNUkkEmWWagUrOLB21Z+6ZaasgchwQ4KiYcpCUGhVGbfvn372gjPg9PhhNHlGREEYe/evb9DxAkHjqaItO/w8T8cOHIq7ipCreBU37tv0y9y0o3JxuMgUxLCilWrNmo0Gq3H44FweOweFIfD0dPY2PiqXAkcTUQQ/P/55J+/4fYGrjowdTXMqfrUn37p9mcyDNpyOdI224lZCIQQpq6+fiXLspzD4YCPz+u839DwaiQSiavvPxkOt6fpyb+9/FtBEONexFpTnFP1z1tX/kzBsUY50jabiVkIHMepFy9ddnMoGCTh0NhxA5fL6WpsbPw/2VI3Abvf++Cpc1c6zskR1+ZFlVvX15R+CeZ4eyFmIaSkpJauXL2qyuN2gyiMPaCrra290Wq1npItdRPgD4Z6Hn/u5Z8HQ+Fxj4OZqNcwHnq1UvuNO1d/P8+UMqfbCzEL4bZtW+9GRHA6naM+jT5M7zc0vCJJkk+uxE3G8aYLr7558Nje8a5N1msYj6w0Q+YP7lv3J4YQvSyJm4XEJASGYVS1dfW1AX8AIvzoTgFCIBAIXLly5R2Z0zchlGLoz6/t+4XL4/uE8GLxCEPUl+Qt+OKG+p8zhChkSeAsIyYh6PX6tMLi4mqvxwMf786fO3fupNvtHvcMv+nC2tvfuOudg3+TIy6GAPn8LbUPVuSY1skR32wjJiGoNVqt2WzO8Hg8Yz6niHjq5Kk3BUG4LtXCEJJEw0+//NZPe+zOgdGfx1o1DGHUqPX/snnJw0aNqkCWBM4iYlqPIEoiVN500zqNWlVEKUVEBFEUpQP7333j9d27f0Qpjfssn1gRRNHrDwSVqxZWr2UZwoxZozDRcvoJF8ci5GcY8oI8z37U1vs2zKE1jzE/OizLppWWl2/Jz88vam9ra+3s6PhQEIQuuIGFxrJM2tM//uahhRWFVcNb6OjQ9rrBA9KkoS11Q3srB7fTDYUZvI5UApcv4P3WM299vtlqf+1G5el6E/MKJUQMOwYGzrZduXLQ5XQ2U0pjOs9vOkDEcDAc5tbUVW9QsAwbj0cARNAoWVVRpnH+vtNtu0RK41oLMVuYlr2PN4LeAZe1rqJkfZ45PQeHjuqbohAAEEx6jUkQRU1jR9+cqCISRgiCKPn8obBi0/LaLQSAxCsEQpCZl5te+/bp9rf94Uj3jcvZ9SFhhAAAYHd5OmvLijblZaZnx1M1DL0qWcLlpevmHbzQ9Zoo0dAkt571JJQQBFEKegNBsnnlwm3xeoSha7mp+twOu8fe2uc+cuNyNv0klBAAAAbcPuvy6vId5jRjuhxCYAgween6iiOtPe/7wkLvDczatJJwQhAlMZxmNOQvvql0BQEk8QoBECFdp0oTJao9fqV3NyToFrqEW+ePCNJL73zwp4ggyrpCant98Y6qnPRb5YxzJpFwHgEAgBcER6pBs6CmtGC+HB4BEEHFEWVumq7mzTMdz0ACnh2ZkEIAALA53L3rFlXfqVMrtXIIAYBCdorWbB3weS73e49Ago0tJKwQPP6AzWJKXbigJH++XEIgiKQ4U1914Hz37lBEck52/9lGwgoBAKjTG3BvWFx9t1rJKeUQAiBCqkZhlCjVnGwfeBsT6GcCEq6xOJqWTtvRCx09su+C3laTf2+Z2bBK7nhvJInsEQARI55AiN26vOYOuTwCIIJWwah0SjanoaVvJyZIwzGhhQAA4PYHe2vLCjZb0o1muYQAiGBJUedc6vd2Wp2BxhuaQZlIeCHwghhgGSbt5tqK9XIKQcESRX6qpmJvc88/JBr7OdUzjYRuIwxC9x49/awkUdkbduWZhvLN1ZavQgKUY8J7BAAAUaI+g1ZVVVOaN18ujwCAwAIwxRm6mjeaep6LSPS6rteUmzkhBAAATyAUvHVJ1Q4lxyrkEgIggkHNap0BXmy2eQ/ALB5kmvUu7Vq50Glr6LK7rdMR9+3zLfdn6JQl0xH39WLOeAREEARRNKyuKV/HTHiya+wegQBCukaR2usNBc73+t6DWeoV5owQAADc/pB39fzSO9L0mhS5hDD0mp+iLjnS4WzwhMWeG5nHqTKnhBAI8/YSS+bi6kLLArmFYFSxBq2CyX3/suMlmIVrFuZMG2EQ+urhxmdDEWFafvFlbWn6zfOz9ZunI+7pZq4JAdp6HScbL1tlGw0c3SDQqzjd/fU534VZ6GnnnBDCEcH5/plL426nl4Oby9JXlWRo1k9X/NPFnBMCAODbx88/M+AJyLJD6+N7BllC2K8szfsPBUt0csR/vZiLQgBvMNzz9qkLr8sR13h9xTXFKWvKTdpZ5RVmXV0mBwgghfgIs3Vp1d3Dv0QXxzjCmM8AgQAweiVj+qDD87pEcdzjfWYac9IjAACcbbPt84f4advguqzQuKbKrJ01h27MSY8AAICIvErBFdWX5S0igCTecYTRHgEQQckAZ1Axlv2X3S8igDBJUmYEc1YIAADuQMi/rqb0Tp1KoZFbCAAIJg2bddEevNTtjcz4nyCcs1UDAEB7r/PoFZujZbri1ykZ9T0LMh4iADP+gK457REQQJQoTVu3oGTjmJ8YjMEj4CQeAZCCWc9lnujyf2QPiBdvZF6vxpwWAgCAN8g7a4ssG7JS9Zly9RpGC4EDZDUKkn2ow/8SxZnbVpjzQgjyEceJ1q6TOrWyoDLXVCpnGwEw+p2SVEXxvsve/Z6w1HYDszopc14IAAC+EN91sLn9hb+9f+avHf1uGy+IaDJostQco5RDCIAUNBzoDnUEXoEZOjOZFMIgCEAjouRs6XEcPnje+tr+s+2vHL9sO69RKDh/OCKoFaxOxTKKqQqhxxtxNnQEdlKEGTnANKdPJL9GFHq1wlJkMlZYUrULlxWb1lVbUsvVHDEalUyKTknUKEmDx/RJMHKUnwRARaBUQk+Q9z15pO83b7Z6H0WEaZkCj5ekEGKHMIQYUjSKospsY3VeqqZAQUi6Wa+orMs11hVnqCwgSRCKCJETna6m5r7AoVPd/ndaHOH9M1UEAEkhTAcsRMuVwgxtDyRJkiRJkiRJklwr/w87M8LF9XFPYwAAAABJRU5ErkJggg==
      mediatype: image/png
  labels:
    alm-owner-kiecloud: kiecloud-operator
    operated-by: kiecloud-operator.v0.1.0
  selector:
    matchLabels:
      alm-owner-kiecloud: kiecloud-operator
      operated-by: kiecloud-operator.v0.1.0
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: true
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: true
  customresourcedefinitions:
    owned:
      - version: v1
        kind: KieApp
        description: An instance of KieApp
        displayName: KieApp
        name: kieapps.app.kiegroup.org
        resources:
          - kind: DeploymentConfig
            version: apps.openshift.io/v1
          - kind: Secret
            version: v1
          - kind: PersistentVolumeClaim
            version: v1
          - kind: ServiceAccount
            version: v1
          - kind: Role
            version: authorization.openshift.io/v1
          - kind: RoleBinding
            version: authorization.openshift.io/v1
          - kind: Service
            version: v1
          - kind: Route
            version: route.openshift.io/v1
        specDescriptors:
          - description: Environment of PAM to deploy.
            displayName: Environment
            path: environment
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
          - description: PAM version to be installed.
            displayName: Version
            path: commonConfig.version
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:label"
        statusDescriptors:
          - description: Deployments for the KieApp environment.
            displayName: Deployments
            path: deployments
            x-descriptors:
              - "urn:alm:descriptor:com.tectonic.ui:podStatuses"
          - description: The address for accessing workbench, if it is deployed.
            displayName: Workbench URL
            path: consoleHost
            x-descriptors:
              - "urn:alm:descriptor:org.w3:link"
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: kie-cloud-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - serviceaccounts
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - "*"
            - apiGroups:
                - app.kiegroup.org
                - apps.openshift.io
                - image.openshift.io
                - build.openshift.io
                - route.openshift.io
              resources:
                - "*"
              verbs:
                - "*"
            - apiGroups:
                - rbac.authorization.k8s.io
              resources:
                - roles
                - rolebindings
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
      deployments:
        - name: kie-cloud-operator
          spec:
            replicas: 1
            strategy:
              type: Recreate
            selector:
              matchLabels:
                name: kie-cloud-operator
            template:
              metadata:
                labels:
                  name: kie-cloud-operator
              spec:
                serviceAccountName: kie-cloud-operator
                containers:
                  - name: kie-cloud-operator
                    image: quay.io/kiegroup/kie-cloud-operator:0.1
                    ports:
                      - containerPort: 60000
                        name: metrics
                    command:
                      - kie-cloud-operator
                    imagePullPolicy: Always
                    readinessProbe:
                      exec:
                        command:
                          - stat
                          - /tmp/operator-sdk-ready
                      initialDelaySeconds: 4
                      periodSeconds: 10
                      failureThreshold: 1
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "kie-cloud-operator"
